import { sql } from "drizzle-orm";
import type { InsertTheme } from "./models/theme";
import { themesTable } from "./models/theme";
import type { Database } from "./index";

export type ThemeEffects = {
  scanlines?: boolean;
  glow?: boolean;
  blur?: boolean;
  grain?: boolean;
  halftone?: boolean;
};

export const THEME_PRESETS = [
  {
    key: "pixel",
    name: "Pixel",
    description: "Arcade night with readable panels, coin-op yellow, and soft scanlines.",
    bg: "#141426",
    surface: "#202044",
    primary: "#ffe45c",
    accent: "#ff6b81",
    textColor: "#fff7d6",
    muted: "#a7a2c8",
    borderStyle: "solid",
    borderRadius: "4px",
    fontHeading: '"Press Start 2P", "VT323", monospace',
    fontBody: '"VT323", ui-monospace, monospace',
    effects: { scanlines: true } satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "glitch",
    name: "Glitch",
    description: "Dark studio neon with cyan focus states and controlled RGB energy.",
    bg: "#090911",
    surface: "#161622",
    primary: "#ff4db8",
    accent: "#30f2dc",
    textColor: "#f8f7ff",
    muted: "#9b98bd",
    borderStyle: "solid",
    borderRadius: "10px",
    fontHeading: '"IBM Plex Mono", "JetBrains Mono", monospace',
    fontBody: '"IBM Plex Sans", system-ui, sans-serif',
    effects: { glow: true } satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "terminal",
    name: "Terminal",
    description: "CRT console with calmer contrast, sharp focus, and readable green text.",
    bg: "#020603",
    surface: "#07150b",
    primary: "#69f58d",
    accent: "#d4ff7a",
    textColor: "#d7ffe0",
    muted: "#7aa884",
    borderStyle: "solid",
    borderRadius: "6px",
    fontHeading: '"JetBrains Mono", "Fira Code", ui-monospace, monospace',
    fontBody: '"JetBrains Mono", ui-monospace, monospace',
    effects: { scanlines: true, glow: true } satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "brutalist",
    name: "Brutalist",
    description: "Poster-like contrast, thick structure, and a cleaner red-orange accent.",
    bg: "#f7f3e8",
    surface: "#fffdf6",
    primary: "#111111",
    accent: "#d85a28",
    textColor: "#111111",
    muted: "#5f5a51",
    borderStyle: "solid",
    borderRadius: "0px",
    fontHeading: '"Space Grotesk", "Helvetica Neue", sans-serif',
    fontBody: '"Inter", "Helvetica Neue", sans-serif',
    effects: {} satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "glassmorphism",
    name: "Glassmorphism",
    description: "Soft daylight glass with stronger text contrast and calmer violet detail.",
    bg: "linear-gradient(135deg, #f6fbf7 0%, #dcecf7 46%, #d8d4ff 100%)",
    surface: "rgba(255, 255, 255, 0.68)",
    primary: "#17324d",
    accent: "#6d5bd0",
    textColor: "#102033",
    muted: "#52677b",
    borderStyle: "solid",
    borderRadius: "22px",
    fontHeading: '"Fraunces", "Georgia", serif',
    fontBody: '"Inter", system-ui, sans-serif',
    effects: { blur: true } satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "bauhaus",
    name: "Bauhaus",
    description: "Gallery cream, geometric primary accents, and confident functional type.",
    bg: "#f8f0da",
    surface: "#fffaf0",
    primary: "#c9302c",
    accent: "#145c9e",
    textColor: "#20201d",
    muted: "#746a58",
    borderStyle: "solid",
    borderRadius: "12px",
    fontHeading: '"Archivo Black", "Futura", sans-serif',
    fontBody: '"Archivo", "Futura", sans-serif',
    effects: {} satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "museum",
    name: "Museum",
    description: "Quiet gallery neutrals, serif headings, and polished archival warmth.",
    bg: "#faf8f3",
    surface: "#fffdf8",
    primary: "#2f2517",
    accent: "#8e6238",
    textColor: "#2f2517",
    muted: "#776b5c",
    borderStyle: "solid",
    borderRadius: "14px",
    fontHeading: '"Fraunces", "Playfair Display", "Georgia", serif',
    fontBody: '"Source Serif Pro", "Georgia", serif',
    effects: {} satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "vaporwave",
    name: "Vaporwave",
    description: "Electric sunset gradients with grounded surfaces and sharper legibility.",
    bg: "linear-gradient(135deg, #ff7ab6 0%, #7c5cff 48%, #28d9e8 100%)",
    surface: "#1a1230",
    primary: "#ffd166",
    accent: "#66ffe0",
    textColor: "#fff7c8",
    muted: "#cbb8ff",
    borderStyle: "double",
    borderRadius: "20px",
    fontHeading: '"Major Mono Display", "Courier New", monospace',
    fontBody: '"Space Mono", "Courier New", monospace',
    effects: { grain: true, glow: true } satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "nature_minimal",
    name: "Nature Minimal",
    description: "Moss, cream, and leaf green with calm whitespace and soft contrast.",
    bg: "#f3f1e8",
    surface: "#fffdf6",
    primary: "#315b42",
    accent: "#6fa77a",
    textColor: "#18291f",
    muted: "#6f7f70",
    borderStyle: "solid",
    borderRadius: "18px",
    fontHeading: '"Fraunces", "Georgia", serif',
    fontBody: '"Inter", system-ui, sans-serif',
    effects: {} satisfies ThemeEffects,
    isSeeded: true,
  },
  {
    key: "anime",
    name: "Anime",
    description: "Manga panels, warm paper, dynamic red, and readable rounded body type.",
    bg: "#fff3d6",
    surface: "#fffaf0",
    primary: "#171717",
    accent: "#d93b32",
    textColor: "#171717",
    muted: "#665b52",
    borderStyle: "solid",
    borderRadius: "16px",
    fontHeading: '"Bangers", "Bebas Neue", "Impact", sans-serif',
    fontBody: '"M PLUS Rounded 1c", "Hiragino Maru Gothic Pro", sans-serif',
    effects: { halftone: true } satisfies ThemeEffects,
    isSeeded: true,
  },
] as const satisfies readonly InsertTheme[];

export async function seedThemes(db: Database): Promise<{ presetCount: number }> {
  await db
    .insert(themesTable)
    .values([...THEME_PRESETS])
    .onConflictDoUpdate({
      target: themesTable.key,
      set: {
        name: sql`excluded.name`,
        description: sql`excluded.description`,
        bg: sql`excluded.bg`,
        surface: sql`excluded.surface`,
        primary: sql`excluded.primary`,
        accent: sql`excluded.accent`,
        textColor: sql`excluded.text_color`,
        muted: sql`excluded.muted`,
        borderStyle: sql`excluded.border_style`,
        borderRadius: sql`excluded.border_radius`,
        fontHeading: sql`excluded.font_heading`,
        fontBody: sql`excluded.font_body`,
        effects: sql`excluded.effects`,
        isSeeded: sql`excluded.is_seeded`,
      },
    });

  return { presetCount: THEME_PRESETS.length };
}
